/*
 * Created on 2025-09-27 ( 14:25:23 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.entities;


import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Administrateur"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="administrateur", schema="public", catalog="memoire_database" )
public class Administrateur implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idadmin", nullable=false)
    private int        idadmin ;

//    @Column(name="idutilisateur", nullable=false)
//    private int        idutilisateur ;

    //--- OTHER DATA FIELDS 
    @Column(name="codedaccess")
    private Integer    codedaccess ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToOne
    @JoinColumn(name="idutilisateur", referencedColumnName="idutilisateur")
    private Utilisateur utilisateur ; 

    /**
     * Constructor
     */
    public Administrateur() {
		super();
    }
    


    public void setIdadmin( int idadmin ) {
        this.idadmin = idadmin ;
    }
    public int getIdadmin() {
        return this.idadmin;
    }

    public void setCodedaccess( Integer codedaccess ) {
        this.codedaccess = codedaccess ;
    }
    public Integer getCodedaccess() {
        return this.codedaccess;
    }

    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Administrateur[");
		sb.append(separator).append("idadmin=").append(idadmin);
		sb.append(separator).append("codedaccess=").append(codedaccess);
		sb.append("]");
		return sb.toString();
	}

}
