/*
 * Created on 2025-09-27 ( 14:25:23 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.entities;


import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Client"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="client", schema="public", catalog="memoire_database" )
public class Client implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idclient", nullable=false)
    private int        idclient ;


//    @Column(name="idutilisateur", nullable=false)
//    private int        idutilisateur ;

//    @Column(name="idlocal")
//    private int idlocalisation;

    @OneToOne
    @JoinColumn(name = "idutilisateur", referencedColumnName = "idutilisateur")
    private Utilisateur utilisateur;

    @OneToOne
    @JoinColumn(name = "idlocal", nullable = false)
    private Localisation localisation;

    /**
     * Constructor
     */
    public Client() {
		super();
    }
    


    public void setIdclient( int idclient ) {
        this.idclient = idclient ;
    }
    public int getIdclient() {
        return this.idclient;
    }



    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Client[");
		sb.append(separator).append("idclient=").append(idclient);
		sb.append("]");
		return sb.toString();
	}

}
