/*
 * Created on 2025-09-27 ( 14:25:24 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import jakarta.persistence.*;

/**
 * JPA entity class for "Contrat"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="contrat", schema="public", catalog="memoire_database" )
public class Contrat implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idcontrat", nullable=false)
    private int        idcontrat ;

    //--- OTHER DATA FIELDS 
    @Column(name="horaires", length=254)
    private String     horaires ;

    @Column(name="jours", length=254)
    private String     jours ;

    @Column(name="montant_salaire")
    private BigDecimal montantSalaire ;

    @Column(name="duree")
    private Integer    duree ;

    /**
     * Constructor
     */
    public Contrat() {
		super();
    }
    
    public void setIdcontrat( int idcontrat ) {
        this.idcontrat = idcontrat ;
    }
    public int getIdcontrat() {
        return this.idcontrat;
    }

    public void setHoraires( String horaires ) {
        this.horaires = horaires ;
    }
    public String getHoraires() {
        return this.horaires;
    }

    public void setJours( String jours ) {
        this.jours = jours ;
    }
    public String getJours() {
        return this.jours;
    }

    public void setMontantSalaire( BigDecimal montantSalaire ) {
        this.montantSalaire = montantSalaire ;
    }
    public BigDecimal getMontantSalaire() {
        return this.montantSalaire;
    }

    public void setDuree( Integer duree ) {
        this.duree = duree ;
    }
    public Integer getDuree() {
        return this.duree;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Contrat[");
		sb.append("horaires=").append(horaires);
		sb.append(separator).append("jours=").append(jours);
		sb.append(separator).append("montantSalaire=").append(montantSalaire);
		sb.append(separator).append("duree=").append(duree);
		sb.append(separator).append("idcontrat=").append(idcontrat);
		sb.append("]");
		return sb.toString();
	}

}
