/*
 * Created on 2025-09-27 ( 14:25:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import jakarta.persistence.*;

/**
 * JPA entity class for "Paiement"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="paiement", schema="public", catalog="memoire_database" )
public class Paiement implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idpaiement", nullable=false)
    private int        idpaiement ;

    //--- OTHER DATA FIELDS 
    @Column(name="montant")
    private BigDecimal montant ;

    @Column(name="methodepaiement", length=254)
    private String     methodepaiement ;

    @Column(name="datepaiement")
    private LocalDate  datepaiement ;

    @Column(name="statutpaiement", length=254)
    private String     statutpaiement ;

    /**
     * Constructor
     */
    public Paiement() {
		super();
    }
    
    public void setIdpaiement( int idpaiement ) {
        this.idpaiement = idpaiement ;
    }
    public int getIdpaiement() {
        return this.idpaiement;
    }

    public void setMontant( BigDecimal montant ) {
        this.montant = montant ;
    }
    public BigDecimal getMontant() {
        return this.montant;
    }

    public void setMethodepaiement( String methodepaiement ) {
        this.methodepaiement = methodepaiement ;
    }
    public String getMethodepaiement() {
        return this.methodepaiement;
    }

    public void setDatepaiement( LocalDate datepaiement ) {
        this.datepaiement = datepaiement ;
    }
    public LocalDate getDatepaiement() {
        return this.datepaiement;
    }

    public void setStatutpaiement( String statutpaiement ) {
        this.statutpaiement = statutpaiement ;
    }
    public String getStatutpaiement() {
        return this.statutpaiement;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Paiement[");
		sb.append("idpaiement=").append(idpaiement);
		sb.append(separator).append("montant=").append(montant);
		sb.append(separator).append("methodepaiement=").append(methodepaiement);
		sb.append(separator).append("datepaiement=").append(datepaiement);
		sb.append(separator).append("statutpaiement=").append(statutpaiement);
		sb.append("]");
		return sb.toString();
	}

}
