/*
 * Created on 2025-09-27 ( 14:25:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.entities;


import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Prestataire"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="prestataire", schema="public", catalog="memoire_database" )
public class Prestataire implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idprestataire", nullable=false, length=254)
    private int     idprestataire ;


    @Column(name="disponibilite")
    private Boolean    disponibilite ;

    @Column(name="description", length=254)
    private String     description ;


    @OneToOne
    @JoinColumn(name="idutilisateur", referencedColumnName="idutilisateur")
    private Utilisateur utilisateur ;



    /**
     * Constructor
     */
    public Prestataire() {
		super();
    }
    


    public int getIdprestataire() {
        return idprestataire;
    }

    public void setIdprestataire(int idprestataire) {
        this.idprestataire = idprestataire;
    }

    public void setDisponibilite(Boolean disponibilite ) {
        this.disponibilite = disponibilite ;
    }
    public Boolean getDisponibilite() {
        return this.disponibilite;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }



    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }



    @Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Prestataire[");
		sb.append(separator).append("idprestataire=").append(idprestataire);
		sb.append(separator).append("disponibilite=").append(disponibilite);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
