/*
 * Created on 2025-09-24 ( 23:19:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.controllers;

import java.util.List;

import memoire.api.memoire_licence.dto.AdministrateurDTO;
import memoire.api.memoire_licence.services.AdministrateurService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



@RestController
@PreAuthorize("hasRole('ADMIN')")
@RequestMapping(value = "/api/v1/administrateur", produces = MediaType.APPLICATION_JSON_VALUE)
public class AdministrateurRestController {

	private static final Logger logger = LoggerFactory.getLogger(AdministrateurRestController.class);

	@Autowired
	private AdministrateurService service ; // injected

	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<AdministrateurDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<AdministrateurDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param idutilisateur
	 * @param idadmin
     * @return 200 or 404
     */
    @GetMapping("/{idutilisateur}/{idadmin}")
    protected ResponseEntity<AdministrateurDTO> findById(@PathVariable int idutilisateur, @PathVariable int idadmin) {
    	logger.debug("REST : GET - findById");
    	AdministrateurDTO administrateurDTO = service.findById(idutilisateur, idadmin);
		if ( administrateurDTO != null ) {
			return ResponseEntity.ok(administrateurDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param administrateurDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody AdministrateurDTO administrateurDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(administrateurDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param idutilisateur
	 * @param idadmin
	 * @param administrateurDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{idutilisateur}/{idadmin}")
	protected ResponseEntity<Void> save(@PathVariable int idutilisateur, @PathVariable int idadmin, @RequestBody AdministrateurDTO administrateurDTO) {
    	logger.debug("REST : PUT - save");
		service.save(idutilisateur, idadmin, administrateurDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param administrateurDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody AdministrateurDTO administrateurDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(administrateurDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param idutilisateur
	 * @param idadmin
	 * @param administrateurDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{idutilisateur}/{idadmin}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable int idutilisateur, @PathVariable int idadmin, @RequestBody AdministrateurDTO administrateurDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(idutilisateur, idadmin, administrateurDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param idutilisateur
	 * @param idadmin
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{idutilisateur}/{idadmin}")
	protected ResponseEntity<Void> deleteById(@PathVariable int idutilisateur, @PathVariable int idadmin) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(idutilisateur, idadmin) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
