/*
 * Created on 2025-09-24 ( 23:19:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.controllers;

import java.util.List;

import memoire.api.memoire_licence.services.ContratService;
import memoire.api.memoire_licence.dto.ContratDTO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



@RestController
@RequestMapping(value = "/api/v1/contrat", produces = MediaType.APPLICATION_JSON_VALUE)
public class ContratRestController {

	private static final Logger logger = LoggerFactory.getLogger(ContratRestController.class);

	@Autowired
	private ContratService service ; // injected
	

    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<ContratDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<ContratDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param idcontrat
     * @return 200 or 404 
     */
    @GetMapping("/{idcontrat}")
    protected ResponseEntity<ContratDTO> findById(@PathVariable int idcontrat) {
    	logger.debug("REST : GET - findById");
    	ContratDTO contratDTO = service.findById(idcontrat);
		if ( contratDTO != null ) {
			return ResponseEntity.ok(contratDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param contratDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody ContratDTO contratDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(contratDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param idcontrat
	 * @param contratDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{idcontrat}")
	protected ResponseEntity<Void> save(@PathVariable int idcontrat, @RequestBody ContratDTO contratDTO) {
    	logger.debug("REST : PUT - save");
		service.save(idcontrat, contratDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param contratDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody ContratDTO contratDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(contratDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param idcontrat
	 * @param contratDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{idcontrat}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable int idcontrat, @RequestBody ContratDTO contratDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(idcontrat, contratDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param idcontrat
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{idcontrat}")
	protected ResponseEntity<Void> deleteById(@PathVariable int idcontrat) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(idcontrat) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
