/*
 * Created on 2025-09-24 ( 23:19:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.controllers;

import java.util.List;

import memoire.api.memoire_licence.dto.response.PrestataireDTO;
import memoire.api.memoire_licence.services.PrestataireService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



@RestController
@RequestMapping(value = "/api/v1/prestataire", produces = MediaType.APPLICATION_JSON_VALUE)
public class PrestataireRestController {

	private static final Logger logger = LoggerFactory.getLogger(PrestataireRestController.class);

	@Autowired
	private PrestataireService service ; // injected
	

	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<PrestataireDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<PrestataireDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param idutilisateur
	 * @param idprestataire
     * @return 200 or 404 
     */
    @GetMapping("/{idutilisateur}/{idprestataire}")
    protected ResponseEntity<PrestataireDTO> findById(@PathVariable int idutilisateur, @PathVariable String idprestataire) {
    	logger.debug("REST : GET - findById");
    	PrestataireDTO prestataireDTO = service.findById(idutilisateur, idprestataire);
		if ( prestataireDTO != null ) {
			return ResponseEntity.ok(prestataireDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param prestataireDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody PrestataireDTO prestataireDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(prestataireDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param idutilisateur
	 * @param idprestataire
	 * @param prestataireDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{idutilisateur}/{idprestataire}")
	protected ResponseEntity<Void> save(@PathVariable int idutilisateur, @PathVariable String idprestataire, @RequestBody PrestataireDTO prestataireDTO) {
    	logger.debug("REST : PUT - save");
		service.save(idutilisateur, idprestataire, prestataireDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param prestataireDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody PrestataireDTO prestataireDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(prestataireDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param idutilisateur
	 * @param idprestataire
	 * @param prestataireDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{idutilisateur}/{idprestataire}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable int idutilisateur, @PathVariable String idprestataire, @RequestBody PrestataireDTO prestataireDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(idutilisateur, idprestataire, prestataireDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param idutilisateur
	 * @param idprestataire
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{idutilisateur}/{idprestataire}")
	protected ResponseEntity<Void> deleteById(@PathVariable int idutilisateur, @PathVariable String idprestataire) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(idutilisateur, idprestataire) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
