/*
 * Created on 2025-09-24 ( 23:19:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.controllers;

import java.util.List;

import memoire.api.memoire_licence.dto.ServiceDTO;
import memoire.api.memoire_licence.services.ServiceForServiceEntity;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



@RestController
@RequestMapping(value = "/api/v1/service", produces = MediaType.APPLICATION_JSON_VALUE)
public class ServiceRestController {

	private static final Logger logger = LoggerFactory.getLogger(ServiceRestController.class);

	@Autowired
	private ServiceForServiceEntity service ; // injected
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<ServiceDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<ServiceDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param idservice
     * @return 200 or 404 
     */
    @GetMapping("/{idservice}")
    protected ResponseEntity<ServiceDTO> findById(@PathVariable int idservice) {
    	logger.debug("REST : GET - findById");
    	ServiceDTO serviceDTO = service.findById(idservice);
		if ( serviceDTO != null ) {
			return ResponseEntity.ok(serviceDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param serviceDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody ServiceDTO serviceDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(serviceDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param idservice
	 * @param serviceDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{idservice}")
	protected ResponseEntity<Void> save(@PathVariable int idservice, @RequestBody ServiceDTO serviceDTO) {
    	logger.debug("REST : PUT - save");
		service.save(idservice, serviceDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param serviceDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody ServiceDTO serviceDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(serviceDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param idservice
	 * @param serviceDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{idservice}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable int idservice, @RequestBody ServiceDTO serviceDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(idservice, serviceDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param idservice
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{idservice}")
	protected ResponseEntity<Void> deleteById(@PathVariable int idservice) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(idservice) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
