/*
 * Created on 2025-09-24 ( 23:19:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.controllers;

import java.util.List;

import memoire.api.memoire_licence.dto.response.UtilisateurDTO;
import memoire.api.memoire_licence.services.UtilisateurService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;



@RestController
@RequestMapping(value = "/api/v1/utilisateur", produces = MediaType.APPLICATION_JSON_VALUE)
public class UtilisateurRestController {

	private static final Logger logger = LoggerFactory.getLogger(UtilisateurRestController.class);

	@Autowired
	private UtilisateurService service ;
	

	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<UtilisateurDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<UtilisateurDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param email
     * @return 200 or 404 
     */
    @GetMapping("/{email}")
    protected ResponseEntity<UtilisateurDTO> findByEmail(@PathVariable String email) {
    	logger.debug("REST : GET - findById");
    	UtilisateurDTO utilisateurDTO = service.findByEmail(email);
		if ( utilisateurDTO != null ) {
			return ResponseEntity.ok(utilisateurDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param utilisateurDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<?> create(@RequestBody UtilisateurDTO utilisateurDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(utilisateurDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).body("Cet email est deja lie a un compte"); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param email
	 * @param utilisateurDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{email}")
	protected ResponseEntity<Void> update(@PathVariable String email, @RequestBody UtilisateurDTO utilisateurDTO) {
    	logger.debug("REST : PUT - save");
		service.update(email, utilisateurDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}



	/**
	 * Delete by PK 
	 *
	 * @param email
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{email}")
	protected ResponseEntity<Void> deleteById(@PathVariable String email) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(email) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
