/*
 * Created on 2025-09-24 ( 23:19:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.repositories;

import memoire.api.memoire_licence.entities.Contrat;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring Data JPA repository for entity "Contrat" <br> 
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface ContratRepository extends CrudRepository<Contrat, Integer> {

	// Insert specific finders here 

	//List<Contrat> findByXxx(String xxx);

	//List<Contrat> findByXxxStartingWith(String xxx);

	//List<Contrat> findByXxxContaining(String xxx);

	//List<Contrat> findByYyy(BigDecimal yyy);

	//List<Contrat> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
