/*
 * Created on 2025-09-24 ( 23:19:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.repositories;

import memoire.api.memoire_licence.entities.Utilisateur;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;

import java.util.Optional;


/**
 * Spring Data JPA repository for entity "Utilisateur" <br> 
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface UtilisateurRepository extends CrudRepository<Utilisateur, Integer> {

    Optional<Utilisateur> findByEmail(String email);

    void deleteByEmail(String email);

	// Insert specific finders here 

	//List<Utilisateur> findByXxx(String xxx);

	//List<Utilisateur> findByXxxStartingWith(String xxx);

	//List<Utilisateur> findByXxxContaining(String xxx);

	//List<Utilisateur> findByYyy(BigDecimal yyy);

	//List<Utilisateur> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
