/*
 * Created on 2025-09-24 ( 23:19:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "Administrateur" ( stored in table "administrateur" )
 *
 * @author Telosys
 *
 */
public class AdministrateurId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private int        idutilisateur ;
    
    private int        idadmin ;
    
    /**
     * Constructor
     */
    public AdministrateurId() {
        super();
    }

    /**
     * Constructor with values
     * @param idutilisateur 
     * @param idadmin 
     */
    public AdministrateurId( Integer idutilisateur, Integer idadmin ) {
        super();
        this.idutilisateur = idutilisateur ;
        this.idadmin = idadmin ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setIdutilisateur( int value ) {
        this.idutilisateur = value;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdadmin( int value ) {
        this.idadmin = value;
    }
    public int getIdadmin() {
        return this.idadmin;
    }


	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		AdministrateurId other = (AdministrateurId) obj; 
		//--- Attribute idutilisateur
		if ( idutilisateur != other.idutilisateur ) return false ; 
		//--- Attribute idadmin
		if ( idadmin != other.idadmin ) return false ; 
		return true; 
	} 
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idutilisateur
		result = prime * result + idutilisateur;
		//--- Attribute idadmin
		result = prime * result + idadmin;
		
		return result; 
	} 
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Administrateur[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idadmin=").append(idadmin);
		sb.append("]");
		return sb.toString();
	}

}
