/*
 * Created on 2025-09-24 ( 23:19:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;


import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Client"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="client", schema="public", catalog="memoire_database" )
@IdClass(ClientId.class)
public class Client implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="idutilisateur", nullable=false)
    private int        idutilisateur ;

    @Id
    @Column(name="idclient", nullable=false)
    private int        idclient ;

    //--- OTHER DATA FIELDS 
    @Column(name="iddemande", nullable=false)
    private int        iddemande ;

    @Column(name="idevaluation", nullable=false)
    private int        idevaluation ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="idevaluation", referencedColumnName="idevaluation", insertable=false, updatable=false)
    private Evaluation evaluation ; 

    @ManyToOne
    @JoinColumn(name="iddemande", referencedColumnName="iddemande", insertable=false, updatable=false)
    private Demandeservice demandeservice ; 

    @ManyToOne
    @JoinColumn(name="idutilisateur", referencedColumnName="idutilisateur", insertable=false, updatable=false)
    private Utilisateur utilisateur ; 

    /**
     * Constructor
     */
    public Client() {
		super();
    }
    
    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdclient( int idclient ) {
        this.idclient = idclient ;
    }
    public int getIdclient() {
        return this.idclient;
    }

    public void setIddemande( int iddemande ) {
        this.iddemande = iddemande ;
    }
    public int getIddemande() {
        return this.iddemande;
    }

    public void setIdevaluation( int idevaluation ) {
        this.idevaluation = idevaluation ;
    }
    public int getIdevaluation() {
        return this.idevaluation;
    }

    public Evaluation getEvaluation() {
        return this.evaluation;
    } 

    public Demandeservice getDemandeservice() {
        return this.demandeservice;
    } 

    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Client[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idclient=").append(idclient);
		sb.append(separator).append("iddemande=").append(iddemande);
		sb.append(separator).append("idevaluation=").append(idevaluation);
		sb.append("]");
		return sb.toString();
	}

}
