/*
 * Created on 2025-09-24 ( 23:19:47 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "Client" ( stored in table "client" )
 *
 * @author Telosys
 *
 */
public class ClientId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private int        idutilisateur ;
    
    private int        idclient ;
    
    /**
     * Constructor
     */
    public ClientId() {
        super();
    }

    /**
     * Constructor with values
     * @param idutilisateur 
     * @param idclient 
     */
    public ClientId( Integer idutilisateur, Integer idclient ) {
        super();
        this.idutilisateur = idutilisateur ;
        this.idclient = idclient ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setIdutilisateur( int value ) {
        this.idutilisateur = value;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdclient( int value ) {
        this.idclient = value;
    }
    public int getIdclient() {
        return this.idclient;
    }


	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ClientId other = (ClientId) obj; 
		//--- Attribute idutilisateur
		if ( idutilisateur != other.idutilisateur ) return false ; 
		//--- Attribute idclient
		if ( idclient != other.idclient ) return false ; 
		return true; 
	} 
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idutilisateur
		result = prime * result + idutilisateur;
		//--- Attribute idclient
		result = prime * result + idclient;
		
		return result; 
	} 
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Client[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idclient=").append(idclient);
		sb.append("]");
		return sb.toString();
	}

}
