/*
 * Created on 2025-09-24 ( 23:19:48 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;

import java.io.Serializable;
import java.time.LocalDate;
import javax.persistence.*;

/**
 * JPA entity class for "Demandeservice"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="demandeservice", schema="public", catalog="memoire_database" )
public class Demandeservice implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="iddemande", nullable=false)
    private int        iddemande ;

    //--- OTHER DATA FIELDS 
    @Column(name="idcontrat", nullable=false)
    private int        idcontrat ;

    @Column(name="idpaiement", nullable=false)
    private int        idpaiement ;

    @Column(name="datededemande")
    private LocalDate  datededemande ;

    @Column(name="statut", length=254)
    private String     statut ;

    @Column(name="detailsdemande", length=254)
    private String     detailsdemande ;

    @Column(name="datederendezvous")
    private LocalDate  datederendezvous ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="idpaiement", referencedColumnName="idpaiement", insertable=false, updatable=false)
    private Paiement   paiement ; 

    @ManyToOne
    @JoinColumn(name="idcontrat", referencedColumnName="idcontrat", insertable=false, updatable=false)
    private Contrat    contrat ; 

    /**
     * Constructor
     */
    public Demandeservice() {
		super();
    }
    
    public void setIddemande( int iddemande ) {
        this.iddemande = iddemande ;
    }
    public int getIddemande() {
        return this.iddemande;
    }

    public void setIdcontrat( int idcontrat ) {
        this.idcontrat = idcontrat ;
    }
    public int getIdcontrat() {
        return this.idcontrat;
    }

    public void setIdpaiement( int idpaiement ) {
        this.idpaiement = idpaiement ;
    }
    public int getIdpaiement() {
        return this.idpaiement;
    }

    public void setDatededemande( LocalDate datededemande ) {
        this.datededemande = datededemande ;
    }
    public LocalDate getDatededemande() {
        return this.datededemande;
    }

    public void setStatut( String statut ) {
        this.statut = statut ;
    }
    public String getStatut() {
        return this.statut;
    }

    public void setDetailsdemande( String detailsdemande ) {
        this.detailsdemande = detailsdemande ;
    }
    public String getDetailsdemande() {
        return this.detailsdemande;
    }

    public void setDatederendezvous( LocalDate datederendezvous ) {
        this.datederendezvous = datederendezvous ;
    }
    public LocalDate getDatederendezvous() {
        return this.datederendezvous;
    }

    public Paiement getPaiement() {
        return this.paiement;
    } 

    public Contrat getContrat() {
        return this.contrat;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Demandeservice[");
		sb.append("iddemande=").append(iddemande);
		sb.append(separator).append("idcontrat=").append(idcontrat);
		sb.append(separator).append("idpaiement=").append(idpaiement);
		sb.append(separator).append("datededemande=").append(datededemande);
		sb.append(separator).append("statut=").append(statut);
		sb.append(separator).append("detailsdemande=").append(detailsdemande);
		sb.append(separator).append("datederendezvous=").append(datederendezvous);
		sb.append("]");
		return sb.toString();
	}

}
