/*
 * Created on 2025-09-24 ( 23:19:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;


import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Prestataire"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="prestataire", schema="public", catalog="memoire_database" )
@IdClass(PrestataireId.class)
public class Prestataire implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="idutilisateur", nullable=false)
    private int        idutilisateur ;

    @Id
    @Column(name="idprestataire", nullable=false, length=254)
    private String     idprestataire ;

    //--- OTHER DATA FIELDS 
    @Column(name="iddemande", nullable=false)
    private int        iddemande ;

    @Column(name="disponibilite")
    private Boolean    disponibilite ;

    @Column(name="description", length=254)
    private String     description ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="iddemande", referencedColumnName="iddemande", insertable=false, updatable=false)
    private Demandeservice demandeservice ; 

    @ManyToOne
    @JoinColumn(name="idutilisateur", referencedColumnName="idutilisateur", insertable=false, updatable=false)
    private Utilisateur utilisateur ; 

    /**
     * Constructor
     */
    public Prestataire() {
		super();
    }
    
    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdprestataire( String idprestataire ) {
        this.idprestataire = idprestataire ;
    }
    public String getIdprestataire() {
        return this.idprestataire;
    }

    public void setIddemande( int iddemande ) {
        this.iddemande = iddemande ;
    }
    public int getIddemande() {
        return this.iddemande;
    }

    public void setDisponibilite( Boolean disponibilite ) {
        this.disponibilite = disponibilite ;
    }
    public Boolean getDisponibilite() {
        return this.disponibilite;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public Demandeservice getDemandeservice() {
        return this.demandeservice;
    } 

    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Prestataire[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idprestataire=").append(idprestataire);
		sb.append(separator).append("iddemande=").append(iddemande);
		sb.append(separator).append("disponibilite=").append(disponibilite);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}

}
