/*
 * Created on 2025-09-24 ( 23:19:50 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Service"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="service", schema="public", catalog="memoire_database" )
public class Service implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="idservice", nullable=false)
    private int        idservice ;

    //--- OTHER DATA FIELDS 
    @Column(name="iddemande")
    private Integer    iddemande ;

    @Column(name="nom", length=254)
    private String     nom ;

    @Column(name="description", length=254)
    private String     description ;

    @Column(name="categorie", length=254)
    private String     categorie ;

    @Column(name="etat")
    private Boolean    etat ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="iddemande", referencedColumnName="iddemande", insertable=false, updatable=false)
    private Demandeservice demandeservice ; 

    /**
     * Constructor
     */
    public Service() {
		super();
    }
    
    public void setIdservice( int idservice ) {
        this.idservice = idservice ;
    }
    public int getIdservice() {
        return this.idservice;
    }

    public void setIddemande( Integer iddemande ) {
        this.iddemande = iddemande ;
    }
    public Integer getIddemande() {
        return this.iddemande;
    }

    public void setNom( String nom ) {
        this.nom = nom ;
    }
    public String getNom() {
        return this.nom;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setCategorie( String categorie ) {
        this.categorie = categorie ;
    }
    public String getCategorie() {
        return this.categorie;
    }

    public void setEtat( Boolean etat ) {
        this.etat = etat ;
    }
    public Boolean getEtat() {
        return this.etat;
    }

    public Demandeservice getDemandeservice() {
        return this.demandeservice;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Service[");
		sb.append("idservice=").append(idservice);
		sb.append(separator).append("iddemande=").append(iddemande);
		sb.append(separator).append("nom=").append(nom);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("categorie=").append(categorie);
		sb.append(separator).append("etat=").append(etat);
		sb.append("]");
		return sb.toString();
	}

}
