/*
 * Created on 2025-09-24 ( 23:19:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package org.demo.persistence.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Utilisateur"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="utilisateur", schema="public", catalog="memoire_database" )
public class Utilisateur implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="idutilisateur", nullable=false)
    private int        idutilisateur ;

    //--- OTHER DATA FIELDS 
    @Column(name="nom", length=254)
    private String     nom ;

    @Column(name="prenom", length=254)
    private String     prenom ;

    @Column(name="telephone")
    private Long       telephone ;

    @Column(name="email", length=254)
    private String     email ;

    @Column(name="adresse", length=254)
    private String     adresse ;

    @Column(name="motdepasse", length=254)
    private String     motdepasse ;

    /**
     * Constructor
     */
    public Utilisateur() {
		super();
    }
    
    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setNom( String nom ) {
        this.nom = nom ;
    }
    public String getNom() {
        return this.nom;
    }

    public void setPrenom( String prenom ) {
        this.prenom = prenom ;
    }
    public String getPrenom() {
        return this.prenom;
    }

    public void setTelephone( Long telephone ) {
        this.telephone = telephone ;
    }
    public Long getTelephone() {
        return this.telephone;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAdresse( String adresse ) {
        this.adresse = adresse ;
    }
    public String getAdresse() {
        return this.adresse;
    }

    public void setMotdepasse( String motdepasse ) {
        this.motdepasse = motdepasse ;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Utilisateur[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("nom=").append(nom);
		sb.append(separator).append("prenom=").append(prenom);
		sb.append(separator).append("telephone=").append(telephone);
		sb.append(separator).append("email=").append(email);
		sb.append(separator).append("adresse=").append(adresse);
		sb.append(separator).append("motdepasse=").append(motdepasse);
		sb.append("]");
		return sb.toString();
	}

}
