/*
 * Created on 2025-09-27 ( 14:25:23 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;

/**
 * DTO class for "Administrateur"
 *
 * @author Telosys
 *
 */
public class AdministrateurDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int idutilisateur ;
    private int idadmin ;
    //--- OTHER DATA FIELDS 
    private Integer codedaccess ;
    //--- LINKS ( RELATIONSHIPS )
    private UtilisateurDTO utilisateur ; 

    /**
     * Constructor
     */
    public AdministrateurDTO() {
		super();
    }
    
    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdadmin( int idadmin ) {
        this.idadmin = idadmin ;
    }
    public int getIdadmin() {
        return this.idadmin;
    }

    public void setCodedaccess( Integer codedaccess ) {
        this.codedaccess = codedaccess ;
    }
    public Integer getCodedaccess() {
        return this.codedaccess;
    }

    public UtilisateurDTO getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Administrateur[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idadmin=").append(idadmin);
		sb.append(separator).append("codedaccess=").append(codedaccess);
		sb.append("]");
		return sb.toString();
	}
}
