/*
 * Created on 2025-09-27 ( 14:25:23 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;

/**
 * DTO class for "Client"
 *
 * @author Telosys
 *
 */
public class ClientDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int idutilisateur ;
    private int idclient ;
    //--- OTHER DATA FIELDS 
    private int iddemande ;
    private int idevaluation ;
    //--- LINKS ( RELATIONSHIPS )
    private EvaluationDTO evaluation ; 
    private DemandeserviceDTO demandeservice ; 
    private UtilisateurDTO utilisateur ; 

    /**
     * Constructor
     */
    public ClientDTO() {
		super();
    }
    
    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdclient( int idclient ) {
        this.idclient = idclient ;
    }
    public int getIdclient() {
        return this.idclient;
    }

    public void setIddemande( int iddemande ) {
        this.iddemande = iddemande ;
    }
    public int getIddemande() {
        return this.iddemande;
    }

    public void setIdevaluation( int idevaluation ) {
        this.idevaluation = idevaluation ;
    }
    public int getIdevaluation() {
        return this.idevaluation;
    }

    public EvaluationDTO getEvaluation() {
        return this.evaluation;
    } 

    public DemandeserviceDTO getDemandeservice() {
        return this.demandeservice;
    } 

    public UtilisateurDTO getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Client[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idclient=").append(idclient);
		sb.append(separator).append("iddemande=").append(iddemande);
		sb.append(separator).append("idevaluation=").append(idevaluation);
		sb.append("]");
		return sb.toString();
	}
}
