/*
 * Created on 2025-09-27 ( 14:25:24 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;
import java.time.LocalDate;

/**
 * DTO class for "Demandeservice"
 *
 * @author Telosys
 *
 */
public class DemandeserviceDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int iddemande ;
    //--- OTHER DATA FIELDS 
    private int idcontrat ;
    private int idpaiement ;
    private LocalDate datededemande ;
    private String statut ;
    private String detailsdemande ;
    private LocalDate datederendezvous ;
    //--- LINKS ( RELATIONSHIPS )
    private PaiementDTO paiement ; 
    private ContratDTO contrat ; 

    /**
     * Constructor
     */
    public DemandeserviceDTO() {
		super();
    }
    
    public void setIddemande( int iddemande ) {
        this.iddemande = iddemande ;
    }
    public int getIddemande() {
        return this.iddemande;
    }

    public void setIdcontrat( int idcontrat ) {
        this.idcontrat = idcontrat ;
    }
    public int getIdcontrat() {
        return this.idcontrat;
    }

    public void setIdpaiement( int idpaiement ) {
        this.idpaiement = idpaiement ;
    }
    public int getIdpaiement() {
        return this.idpaiement;
    }

    public void setDatededemande( LocalDate datededemande ) {
        this.datededemande = datededemande ;
    }
    public LocalDate getDatededemande() {
        return this.datededemande;
    }

    public void setStatut( String statut ) {
        this.statut = statut ;
    }
    public String getStatut() {
        return this.statut;
    }

    public void setDetailsdemande( String detailsdemande ) {
        this.detailsdemande = detailsdemande ;
    }
    public String getDetailsdemande() {
        return this.detailsdemande;
    }

    public void setDatederendezvous( LocalDate datederendezvous ) {
        this.datederendezvous = datederendezvous ;
    }
    public LocalDate getDatederendezvous() {
        return this.datederendezvous;
    }

    public PaiementDTO getPaiement() {
        return this.paiement;
    } 

    public ContratDTO getContrat() {
        return this.contrat;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Demandeservice[");
		sb.append("iddemande=").append(iddemande);
		sb.append(separator).append("idcontrat=").append(idcontrat);
		sb.append(separator).append("idpaiement=").append(idpaiement);
		sb.append(separator).append("datededemande=").append(datededemande);
		sb.append(separator).append("statut=").append(statut);
		sb.append(separator).append("detailsdemande=").append(detailsdemande);
		sb.append(separator).append("datederendezvous=").append(datederendezvous);
		sb.append("]");
		return sb.toString();
	}
}
