/*
 * Created on 2025-09-27 ( 14:25:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;
import java.time.LocalDate;

/**
 * DTO class for "Evaluation"
 *
 * @author Telosys
 *
 */
public class EvaluationDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int idevaluation ;
    //--- OTHER DATA FIELDS 
    private int idutilisateur ;
    private String idprestataire ;
    private Integer note ;
    private String commentaire ;
    private LocalDate dateservice ;
    //--- LINKS ( RELATIONSHIPS )
    private PrestataireDTO prestataire ; 

    /**
     * Constructor
     */
    public EvaluationDTO() {
		super();
    }
    
    public void setIdevaluation( int idevaluation ) {
        this.idevaluation = idevaluation ;
    }
    public int getIdevaluation() {
        return this.idevaluation;
    }

    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdprestataire( String idprestataire ) {
        this.idprestataire = idprestataire ;
    }
    public String getIdprestataire() {
        return this.idprestataire;
    }

    public void setNote( Integer note ) {
        this.note = note ;
    }
    public Integer getNote() {
        return this.note;
    }

    public void setCommentaire( String commentaire ) {
        this.commentaire = commentaire ;
    }
    public String getCommentaire() {
        return this.commentaire;
    }

    public void setDateservice( LocalDate dateservice ) {
        this.dateservice = dateservice ;
    }
    public LocalDate getDateservice() {
        return this.dateservice;
    }

    public PrestataireDTO getPrestataire() {
        return this.prestataire;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Evaluation[");
		sb.append("idevaluation=").append(idevaluation);
		sb.append(separator).append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idprestataire=").append(idprestataire);
		sb.append(separator).append("note=").append(note);
		sb.append(separator).append("commentaire=").append(commentaire);
		sb.append(separator).append("dateservice=").append(dateservice);
		sb.append("]");
		return sb.toString();
	}
}
