/*
 * Created on 2025-09-27 ( 14:25:25 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;

/**
 * DTO class for "Localisation"
 *
 * @author Telosys
 *
 */
public class LocalisationDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int idlocal ;
    //--- OTHER DATA FIELDS 
    private String latitude ;
    private String longitude ;

    /**
     * Constructor
     */
    public LocalisationDTO() {
		super();
    }
    
    public void setIdlocal( int idlocal ) {
        this.idlocal = idlocal ;
    }
    public int getIdlocal() {
        return this.idlocal;
    }

    public void setLatitude( String latitude ) {
        this.latitude = latitude ;
    }
    public String getLatitude() {
        return this.latitude;
    }

    public void setLongitude( String longitude ) {
        this.longitude = longitude ;
    }
    public String getLongitude() {
        return this.longitude;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Localisation[");
		sb.append("idlocal=").append(idlocal);
		sb.append(separator).append("latitude=").append(latitude);
		sb.append(separator).append("longitude=").append(longitude);
		sb.append("]");
		return sb.toString();
	}
}
