/*
 * Created on 2025-09-27 ( 14:25:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;

/**
 * DTO class for "Prestataire"
 *
 * @author Telosys
 *
 */
public class PrestataireDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private int idutilisateur ;
    private String idprestataire ;
    //--- OTHER DATA FIELDS 
    private int iddemande ;
    private Boolean disponibilite ;
    private String description ;
    //--- LINKS ( RELATIONSHIPS )
    private DemandeserviceDTO demandeservice ; 
    private UtilisateurDTO utilisateur ; 

    /**
     * Constructor
     */
    public PrestataireDTO() {
		super();
    }
    
    public void setIdutilisateur( int idutilisateur ) {
        this.idutilisateur = idutilisateur ;
    }
    public int getIdutilisateur() {
        return this.idutilisateur;
    }

    public void setIdprestataire( String idprestataire ) {
        this.idprestataire = idprestataire ;
    }
    public String getIdprestataire() {
        return this.idprestataire;
    }

    public void setIddemande( int iddemande ) {
        this.iddemande = iddemande ;
    }
    public int getIddemande() {
        return this.iddemande;
    }

    public void setDisponibilite( Boolean disponibilite ) {
        this.disponibilite = disponibilite ;
    }
    public Boolean getDisponibilite() {
        return this.disponibilite;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public DemandeserviceDTO getDemandeservice() {
        return this.demandeservice;
    } 

    public UtilisateurDTO getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Prestataire[");
		sb.append("idutilisateur=").append(idutilisateur);
		sb.append(separator).append("idprestataire=").append(idprestataire);
		sb.append(separator).append("iddemande=").append(iddemande);
		sb.append(separator).append("disponibilite=").append(disponibilite);
		sb.append(separator).append("description=").append(description);
		sb.append("]");
		return sb.toString();
	}
}
