/*
 * Created on 2025-09-27 ( 14:25:27 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto;

import java.io.Serializable;

/**
 * DTO class for "Utilisateur"
 *
 * @author Telosys
 *
 */
public class UtilisateurDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- OTHER DATA FIELDS 
    private String nom ;
    private String prenom ;
    private Long telephone ;
    private String email ;
    private String adresse ;
    private String motdepasse ;

    /**
     * Constructor
     */
    public UtilisateurDTO() {
		super();
    }
    

    public void setNom( String nom ) {
        this.nom = nom ;
    }
    public String getNom() {
        return this.nom;
    }

    public void setPrenom( String prenom ) {
        this.prenom = prenom ;
    }
    public String getPrenom() {
        return this.prenom;
    }

    public void setTelephone( Long telephone ) {
        this.telephone = telephone ;
    }
    public Long getTelephone() {
        return this.telephone;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAdresse( String adresse ) {
        this.adresse = adresse ;
    }
    public String getAdresse() {
        return this.adresse;
    }

    public void setMotdepasse( String motdepasse ) {
        this.motdepasse = motdepasse ;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Utilisateur[");
		sb.append(separator).append("nom=").append(nom);
		sb.append(separator).append("prenom=").append(prenom);
		sb.append(separator).append("telephone=").append(telephone);
		sb.append(separator).append("email=").append(email);
		sb.append(separator).append("adresse=").append(adresse);
		sb.append(separator).append("motdepasse=").append(motdepasse);
		sb.append("]");
		return sb.toString();
	}
}
