/*
 * Created on 2025-09-27 ( 14:25:23 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.response;

import java.io.Serializable;

/**
 * DTO class for "Administrateur"
 *
 * @author Telosys
 *
 */
public class AdministrateurDTO implements Serializable {

    private static final long serialVersionUID = 1L;


    private Integer codedaccess ;
    //--- LINKS ( RELATIONSHIPS )
    private UtilisateurDTO utilisateur ; 

    /**
     * Constructor
     */
    public AdministrateurDTO() {
		super();
    }
    


    public void setCodedaccess( Integer codedaccess ) {
        this.codedaccess = codedaccess ;
    }
    public Integer getCodedaccess() {
        return this.codedaccess;
    }

    public UtilisateurDTO getUtilisateur() {
        return this.utilisateur;
    }


	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Administrateur[");
		sb.append(separator).append("codedaccess=").append(codedaccess);
		sb.append("]");
		return sb.toString();
	}
}
