/*
 * Created on 2025-09-27 ( 14:25:23 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.response;

import memoire.api.memoire_licence.entities.Utilisateur;

import java.io.Serializable;

/**
 * DTO class for "Client"
 *
 * @author Telosys
 *
 */
public class ClientDTO implements Serializable {

    private static final long serialVersionUID = 1L;

	private String nom ;


	private String prenom ;


	private Long telephone ;


	private String email ;


	private String adresse ;


	private String motdepasse ;

    private Utilisateur utilisateur ;

    /**
     * Constructor
     */
    public ClientDTO() {
		super();
    }

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public void initialise(){
		this.prenom=utilisateur.getPrenom();
		this.nom=utilisateur.getNom();
		this.telephone=utilisateur.getTelephone();
		this.email=utilisateur.getEmail();
		this.adresse=utilisateur.getAdresse();
		this.motdepasse=utilisateur.getMotdepasse();
	}

	public Utilisateur getUtilisateur() {
        return this.utilisateur;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Client[");
		sb.append("]");
		return sb.toString();
	}
}
