/*
 * Created on 2025-09-27 ( 14:25:24 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.response;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DTO class for "Contrat"
 *
 * @author Telosys
 *
 */
public class ContratDTO implements Serializable {

    private static final long serialVersionUID = 1L;


    //--- OTHER DATA FIELDS 
    private String horaires ;
    private String jours ;
    private BigDecimal montantSalaire ;
    private Integer duree ;

    /**
     * Constructor
     */
    public ContratDTO() {
		super();
    }
    


    public void setHoraires( String horaires ) {
        this.horaires = horaires ;
    }
    public String getHoraires() {
        return this.horaires;
    }

    public void setJours( String jours ) {
        this.jours = jours ;
    }
    public String getJours() {
        return this.jours;
    }

    public void setMontantSalaire( BigDecimal montantSalaire ) {
        this.montantSalaire = montantSalaire ;
    }
    public BigDecimal getMontantSalaire() {
        return this.montantSalaire;
    }

    public void setDuree( Integer duree ) {
        this.duree = duree ;
    }
    public Integer getDuree() {
        return this.duree;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Contrat[");
		sb.append("horaires=").append(horaires);
		sb.append(separator).append("jours=").append(jours);
		sb.append(separator).append("montantSalaire=").append(montantSalaire);
		sb.append(separator).append("duree=").append(duree);
		sb.append("]");
		return sb.toString();
	}
}
