/*
 * Created on 2025-09-27 ( 14:25:26 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.response;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * DTO class for "Paiement"
 *
 * @author Telosys
 *
 */
public class PaiementDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- OTHER DATA FIELDS 
    private BigDecimal montant ;
    private String methodepaiement ;
    private LocalDate datepaiement ;
    private String statutpaiement ;

    /**
     * Constructor
     */
    public PaiementDTO() {
		super();
    }
    

    public void setMontant( BigDecimal montant ) {
        this.montant = montant ;
    }
    public BigDecimal getMontant() {
        return this.montant;
    }

    public void setMethodepaiement( String methodepaiement ) {
        this.methodepaiement = methodepaiement ;
    }
    public String getMethodepaiement() {
        return this.methodepaiement;
    }

    public void setDatepaiement( LocalDate datepaiement ) {
        this.datepaiement = datepaiement ;
    }
    public LocalDate getDatepaiement() {
        return this.datepaiement;
    }

    public void setStatutpaiement( String statutpaiement ) {
        this.statutpaiement = statutpaiement ;
    }
    public String getStatutpaiement() {
        return this.statutpaiement;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Paiement[");
		sb.append(separator).append("montant=").append(montant);
		sb.append(separator).append("methodepaiement=").append(methodepaiement);
		sb.append(separator).append("datepaiement=").append(datepaiement);
		sb.append(separator).append("statutpaiement=").append(statutpaiement);
		sb.append("]");
		return sb.toString();
	}
}
