/*
 * Created on 2025-09-27 ( 14:25:27 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package memoire.api.memoire_licence.dto.response;

import java.io.Serializable;

/**
 * DTO class for "Service"
 *
 * @author Telosys
 *
 */
public class ServiceDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- OTHER DATA FIELDS 
    private Integer iddemande ;
    private String nom ;
    private String description ;
    private String categorie ;
    private Boolean etat ;
    //--- LINKS ( RELATIONSHIPS )
    private DemandeserviceDTO demandeservice ; 

    /**
     * Constructor
     */
    public ServiceDTO() {
		super();
    }


    public void setIddemande( Integer iddemande ) {
        this.iddemande = iddemande ;
    }
    public Integer getIddemande() {
        return this.iddemande;
    }

    public void setNom( String nom ) {
        this.nom = nom ;
    }
    public String getNom() {
        return this.nom;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    public void setCategorie( String categorie ) {
        this.categorie = categorie ;
    }
    public String getCategorie() {
        return this.categorie;
    }

    public void setEtat( Boolean etat ) {
        this.etat = etat ;
    }
    public Boolean getEtat() {
        return this.etat;
    }

    public DemandeserviceDTO getDemandeservice() {
        return this.demandeservice;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("Service[");
		sb.append(separator).append("iddemande=").append(iddemande);
		sb.append(separator).append("nom=").append(nom);
		sb.append(separator).append("description=").append(description);
		sb.append(separator).append("categorie=").append(categorie);
		sb.append(separator).append("etat=").append(etat);
		sb.append("]");
		return sb.toString();
	}
}
